server:
  port: 8081

spring:
  application:
    name: dream-journey-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user_route
          uri: lb://dream-journey-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: user_admin_route
          uri: lb://dream-journey-user
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: hotel_category_route
          uri: lb://dream-journey-category
          predicates:
            - Path=/api/hotel/category/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}